### ISSUE TITLE
cannot receive opType notified_read_message

### ISSUE THREAD

**Issue by alfathdirk** [alfathdirk/LineAlphatJS#1]
we couldn't check who has read message on operation

**Comment by merkremont** [comment]
Use line.thrift from 
https://github.com/cslinmiso/LINE-instant-messenger-protocol/blob/master/line.thrift
or
https://github.com/bshillingford/python-line/blob/master/line/line.thrift

**Comment by merkremont** [comment]
```
if(operation.type == 55) { // read message notified
    group_id = operation.param1
    user_mid = operation.param2
}
```

**Comment by alfathdirk** [comment]
i know, there is specification from thrift line_ttypes, when i looked on chat, operation give me number 28 not 55 and not provide param2 as groupid
@merkremont

**Comment by urutbatur** [comment]
bang, nyari command bot nya dmna

**Comment by alfathdirk** [comment]
closed
