### ISSUE TITLE
Stopped after QR code showed

### ISSUE THREAD

**Issue by tbzh** [alfathdirk/LineAlphatJS#2]
System: Windows 10 (64-bit)
Node: v6.11.2

After I typed
`cd LineAlphatJS`
`npm install`
`npm start` 
on my CMD, the program was starting, and then showed QR code. But, the program suddenly stopped after that. This was the error:
`(node:2728) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'result' of undefined`
Then, I tried again. The error changed a little bit:

`(node:4780) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'result' of undefined`

There is no problem with my connection. Hope you can help @alfathdirk :'D

**Comment by alfathdirk** [comment]
Hi @ztrstn , please update your nodejs and re-pull this source

thanks

**Comment by CyberTKR** [comment]
node:3927) UnhandledPromiseRejectionWarning: Unhandled promise rejection (
rejection id: 1): TalkException: TalkException                             
(node:3927) [DEP0018] DeprecationWarning: Unhandled promise rejections are 
deprecated. In the future, promise rejections that are not handled will ter
minate the Node.js process with a non-zero exit code.      

@alfathdirk I enter with Qr code but it stops and gives this error..
Can you help..
