### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by lalauya1122** [alfathdirk/LineAlphatJS#31]
node:3222) UnhandledPromiseRejectionWarning: Unhandled promise rejection (
rejection id: 1): TalkException: TalkException                             
(node:3222) [DEP0018] DeprecationWarning: Unhandled promise rejections are 
deprecated. In the future, promise rejections that are not handled will ter
minate the Node.js process with a non-zero exit code.                      
cabox@box-codeanywhere:~/workspace/alphat-new-generation$

**Comment by Ariswandi255** [comment]
Engga respons bgt antijz nya bro

**Comment by Leonaldofirmansyah** [comment]
emang masih work bot nya?

**Comment by alfathdirk** [comment]
@Leonaldofirmansyah Udah lama ga di oprek ky nya masih deh

**Comment by Leonaldofirmansyah** [comment]
wkwkwkwkkw

**Comment by Ariswandi255** [comment]
ajarin bang napa

Pada tanggal Sen, 22 Apr 2019 11.59, Leonaldofirmansyah <
notifications@github.com> menulis:

> wkwkwkwkkw
>

**Comment by Leonaldofirmansyah** [comment]
bot alphat apa bisa masih aktif??
