### ISSUE TITLE
cannot login with qr

### ISSUE THREAD

**Issue by alfathdirk** [alfathdirk/LineAlphatJS#4]

**Comment by cahyadarma30** [comment]
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "bot"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! linealphatjs@0.1.0 bot: `node ./src/bot.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the linealphatjs@0.1.0 bot script 'node ./src/bot.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the linealphatjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./src/bot.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs linealphatjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls linealphatjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/LineAlphatJS/LineAlphatJS/npm-debug.log

npm ERR! Linux 2.6.32-696.10.1.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! linealphatjs@0.1.0 start: `npm run bot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the linealphatjs@0.1.0 start script 'npm run bot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the linealphatjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run bot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs linealphatjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls linealphatjs
npm ERR! There is likely additional logging output above.

**Comment by cahyadarma30** [comment]
the old one script is better lol its working successfully on people but where i can download it?

**Comment by alfathdirk** [comment]
@cahyadarma30 the latest version need node > 8

**Comment by cahyadarma30** [comment]
@alfathdirk then is no qr link show, check your instagram i send you a message

**Comment by alfathdirk** [comment]
@cahyadarma30 closed !
