### ISSUE TITLE
他的作用?

### ISSUE THREAD

**Issue by lalauya1122** [alfathdirk/LineAlphatJS#7]
他的指令??

他的用途??

help??

**Comment by faisalpepe** [comment]
Help. How to get "authtoken" and "certificate" ?

**Comment by tbzh** [comment]
这个是 LINE  BOT
如果你还有问题，你可以问我。 LINEID： IDLINEGUE
@lalauya1122 

npm start, scan QR, and the 'authtoken' and 'certificate' will appear
@faisalpepe 
@
